/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'
import { Route as AuthZchatCallbackRouteImport } from './routes/auth.zchat.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthZchatCallbackRoute = AuthZchatCallbackRouteImport.update({
  id: '/auth/zchat/callback',
  path: '/auth/zchat/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$slug': typeof GamesSlugRoute
  '/auth/zchat/callback': typeof AuthZchatCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$slug': typeof GamesSlugRoute
  '/auth/zchat/callback': typeof AuthZchatCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$slug': typeof GamesSlugRoute
  '/auth/zchat/callback': typeof AuthZchatCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/$slug' | '/auth/zchat/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/$slug' | '/auth/zchat/callback'
  id: '__root__' | '/' | '/games/$slug' | '/auth/zchat/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesSlugRoute: typeof GamesSlugRoute
  AuthZchatCallbackRoute: typeof AuthZchatCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/zchat/callback': {
      id: '/auth/zchat/callback'
      path: '/auth/zchat/callback'
      fullPath: '/auth/zchat/callback'
      preLoaderRoute: typeof AuthZchatCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesSlugRoute: GamesSlugRoute,
  AuthZchatCallbackRoute: AuthZchatCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
